ecoView/src/Entity/Association.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\AssociationRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass=AssociationRepository::class)
 */
class Association
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ass_nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ass_code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ass_description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ass_adresse;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $ass_cp;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ass_ville;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="associations")
     */
    private $ass_membres;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ass_site;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $ass_created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $ass_added_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ass_logo;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="associationsGerees")
     */
    private $ass_president;

    public function __construct()
    {
        $this->ass_members = new ArrayCollection();
        $this->ass_added_at = new DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAssNom(): ?string
    {
        return $this->ass_nom;
    }

    public function setAssNom(string $ass_nom): self
    {
        $this->ass_nom = $ass_nom;

        return $this;
    }

    public function getAssCode(): ?string
    {
        return $this->ass_code;
    }

    public function setAssCode(string $ass_code): self
    {
        $this->ass_code = $ass_code;

        return $this;
    }

    public function getAssDescription(): ?string
    {
        return $this->ass_description;
    }

    public function setAssDescription(string $ass_description): self
    {
        $this->ass_description = $ass_description;

        return $this;
    }

    public function getAssAdresse(): ?string
    {
        return $this->ass_adresse;
    }

    public function setAssAdresse(?string $ass_adresse): self
    {
        $this->ass_adresse = $ass_adresse;

        return $this;
    }

    public function getAssCp(): ?int
    {
        return $this->ass_cp;
    }

    public function setAssCp(?int $ass_cp): self
    {
        $this->ass_cp = $ass_cp;

        return $this;
    }

    public function getAssVille(): ?string
    {
        return $this->ass_ville;
    }

    public function setAssVille(string $ass_ville): self
    {
        $this->ass_ville = $ass_ville;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getAssMembres(): Collection
    {
        return $this->ass_membres;
    }

    public function addAssMember(User $assMembre): self
    {
        if (!$this->ass_membres->contains($assMembre)) {
            $this->ass_membres[] = $assMembre;
        }

        return $this;
    }

    public function removeAssMembre(User $assMembre): self
    {
        if ($this->ass_membres->contains($assMembre)) {
            $this->ass_membres->removeElement($assMembre);
        }

        return $this;
    }

    public function getAssSite(): ?string
    {
        return $this->ass_site;
    }

    public function setAssSite(?string $ass_site): self
    {
        $this->ass_site = $ass_site;

        return $this;
    }

    public function getAssCreatedAt(): ?\DateTimeInterface
    {
        return $this->ass_created_at;
    }

    public function setAssCreatedAt(?\DateTimeInterface $ass_created_at): self
    {
        $this->ass_created_at = $ass_created_at;

        return $this;
    }

    public function getAssAddedAt(): ?\DateTimeInterface
    {
        return $this->ass_added_at;
    }

    public function setAssAddedAt(\DateTimeInterface $ass_added_at): self
    {
        $this->ass_added_at = $ass_added_at;

        return $this;
    }

    public function getAssLogo(): ?string
    {
        return $this->ass_logo;
    }

    public function setAssLogo(?string $ass_logo): self
    {
        $this->ass_logo = $ass_logo;

        return $this;
    }

    public function getAssPresident(): ?User
    {
        return $this->ass_president;
    }

    public function setAssPresident(?User $ass_president): self
    {
        $this->ass_president = $ass_president;

        return $this;
    }
}

ecoView/src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"id"}, message="There is already an account with this id")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $user_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $user_password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $user_email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $user_ip;

    /**
     * @ORM\Column(type="datetime")
     */
    private $user_created_at;

    /**
     * @ORM\Column(type="integer")
     */
    private $user_clics;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $role;

    /**
     * @ORM\ManyToMany(targetEntity=Association::class, mappedBy="ass_membres")
     */
    private $associations;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\OneToMany(targetEntity=Association::class, mappedBy="ass_president")
     */
    private $associationsGerees;

    public function __construct()
    {
        $this->associations = new ArrayCollection();
        $this->associationsGerees = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->user_name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserName(): ?string
    {
        return $this->user_name;
    }

    public function setUserName(string $user_name): self
    {
        $this->user_name = $user_name;

        return $this;
    }

    public function getUserPassword(): ?string
    {
        return $this->user_password;
    }

    public function setUserPassword(string $user_password): self
    {
        $this->user_password = $user_password;

        return $this;
    }

    public function getUserEmail(): ?string
    {
        return $this->user_email;
    }

    public function setUserEmail(string $user_email): self
    {
        $this->user_email = $user_email;

        return $this;
    }

    public function getUserIp(): ?string
    {
        return $this->user_ip;
    }

    public function setUserIp(?string $user_ip): self
    {
        $this->user_ip = $user_ip;

        return $this;
    }

    public function getUserCreatedAt(): ?\DateTimeInterface
    {
        return $this->user_created_at;
    }

    public function setUserCreatedAt(\DateTimeInterface $user_created_at): self
    {
        $this->user_created_at = $user_created_at;

        return $this;
    }

    public function getUserClics(): ?int
    {
        return $this->user_clics;
    }

    public function setUserClics(int $user_clics): self
    {
        $this->user_clics = $user_clics;

        return $this;
    }

    public function getRoles(): ?array
    {
        return [$this->role];
    }

    public function setRoles(?string $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getUserame(): ?string
    {
        return $this->user_name;
    }

    public function getPassword(){
        return $this->user_password;
    }
    
    public function getSalt(){}

    public function eraseCredentials(){}

    /**
     * @return Collection|Association[]
     */
    public function getAssociations(): Collection
    {
        return $this->associations;
    }

    public function addAssociation(Association $association): self
    {
        if (!$this->associations->contains($association)) {
            $this->associations[] = $association;
            $association->addAssMember($this);
        }

        return $this;
    }

    public function addAssociations(Array $associations)
    {
        foreach($associations as $association){
            $this->addAssociation($association);
        }

        return $this;
    }

    public function removeAssociation(Association $association): self
    {
        if ($this->associations->contains($association)) {
            $this->associations->removeElement($association);
            $association->removeAssMember($this);
        }

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(?string $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection|Association[]
     */
    public function getAssociationsGerees(): Collection
    {
        return $this->associationsGerees;
    }

    public function addAssociationsGeree(Association $associationsGeree): self
    {
        if (!$this->associationsGerees->contains($associationsGeree)) {
            $this->associationsGerees[] = $associationsGeree;
            $associationsGeree->setAssPresident($this);
        }

        return $this;
    }

    public function removeAssociationsGeree(Association $associationsGeree): self
    {
        if ($this->associationsGerees->contains($associationsGeree)) {
            $this->associationsGerees->removeElement($associationsGeree);
            // set the owning side to null (unless already changed)
            if ($associationsGeree->getAssPresident() === $this) {
                $associationsGeree->setAssPresident(null);
            }
        }

        return $this;
    }
}

ecoView/src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('user_name')
            ->add('user_email')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

ecoView/src/Controller/UserController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use App\Repository\AssociationRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="user_index", methods={"GET"})
     */
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="user_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // dd((new DateTime())->format('Y-m-d H:i:s'));
            $user->setUserCreatedAt(new DateTime());
            $user->setUserIp($_SERVER['REMOTE_ADDR']);
            $user->setUserClics(0);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }



    /**
     * @Route("/add_assoc", name="user_add_assoc")
     */
    public function add_assoc(Request $request, AssociationRepository $assoc_repo)
    {
        $user = $this->getUser();
        $associations = $assoc_repo->findAll();
        $form = $request->request;
        if (count($form) > 0){
            foreach($form as $key=>$value)
                $assoc[] = $key;  
            $assocs_to_add = $assoc_repo->findByIds($assoc);
            // dd($assocs_to_add);
            $res = $user->addAssociations($assocs_to_add);
            // dd($res);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->render('user/show.html.twig',compact('associations','user'));
        }
        return $this->render('user/add_assoc.html.twig',compact('associations','user'));
    }

    /**
     * @Route("/{id}", name="user_show", methods={"GET"})
     */
    public function show(UserRepository $userRepo, $id): Response
    {
        $user = $userRepo->findOneBy(['id'=>$id]);
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, User $user): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_delete", methods={"DELETE"})
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getUser_id(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_index');
    }
}

ecoView/templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

ecoView/templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

ecoView/templates/user/add_assoc.html.twig
{% extends "base.html.twig" %}

{% block title "Add association" %}

{% block styles %}
    {{ encore_entry_link_tags('add_assoc') }}
{% endblock %}

{% block body %}
<form action="" method="POST">
    <input type="submit" value="Validate" class="btn btn-outline-primary">
    <div class="container-fluid row" id="flex">
        {% set i = 0 %}
        {% for association in associations %}
        <div class="row m-3 col-4">
            <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-dark active">
                    <input type="checkbox" name="{{association.Id}}" id="assoc_{{i}}" autocomplete="off">
                </label>
            </div>
            <div class="media bg-dark w-75">
                <a class="d-flex" href="#">
                    <img src="{{ asset('img/logo/' ~ association.assLogo) }}" alt="" class="ass_logo">
                </a>
                <div class="media-body">
                    <h5>{{ association.assNom }}</h5>
                    {{ association.assDescription }}
                </div>
            </div> 
        </div>   
        {% set i = i+1 %}
        {% endfor %}
    </div>
</form>
    
{% endblock %}

ecoView/templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Edit User</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('user_index') }}">back to list</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

ecoView/templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <h1>User index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>User's name</th>
                <th>User's email</th>
                <th>User's ip</th>
                <th>User created at</th>
                <th>User nb of clics</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.userName }}</td>
                <td>{{ user.userEmail }}</td>
                <td>{{ user.userIp }}</td>
                <td>{{ user.userCreatedAt | date('Y-m-d H:i:s') }}</td>
                <td>{{ user.userClics }}</td>
                <td>
                    <a href="{{ path('user_show', {'id': user.id}) }}">show</a>
                    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('user_new') }}">Create new</a>
{% endblock %}

ecoView/templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('user_index') }}">back to list</a>
{% endblock %}

ecoView/templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{user}}{% endblock %}

{% block styles %}
    {{ encore_entry_link_tags('add_assoc') }}
{% endblock %}

{% block body %}
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="true">Profile</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="associations-tab" data-toggle="tab" href="#associations" role="tab" aria-controls="associations" aria-selected="false">Associations</a>
    </li>
  </ul>
  <div class="tab-content" id="myTabContent">
  {#  onglet Profile #}
    <div class="tab-pane fade show active" id="profile" role="tabpanel" aria-labelledby="profile-tab">
      <table class="table w-50">
              <tbody>
                  <tr>
                      <th>Name :</th>
                      <td>{{ user.userName }}</td>
                  </tr>
                  <tr>
                      <th>Email : </th>
                      <td>{{ user.userEmail }}</td>
                  </tr>
                  <tr>
                      <th>Created at :</th>
                      <td>{{ user.userCreatedAt ? user.userCreatedAt|date('Y-m-d H:i:s') : '' }}</td>
                  </tr>
                  <tr>
                      <th>Videos watched :</th>
                      <td>{{ user.userClics }}</td>
                  </tr>
              </tbody>
          </table>
      </div>

      {# onglet associations #}
    <div class="tab-pane fade container" id="associations" role="tabpanel" aria-labelledby="associations-tab">
      <a class="btn btn-outline-primary" href="{{ path('user_add_assoc') }}">Add</a>
      {% if user.associationsGerees %}
      <div class="d-flex flex-row justify-content-between">
        {% for association in user.associationsGerees %}
          <div class="media bg-dark p-3 m-3 rounded">
            <a class="d-flex" href="#">
              <img src="{{ asset( 'img/logo/' ~ association.assLogo ) }}"  class="ass_logo" alt="">
            </a>
            <div class="media-body">
              <h5>{{association.assNom}}</h5>
              <p>{{association.assDescription}}</p>
              <a href="{{ path('association_edit', {"id": association.id}) }}" class="btn btn-outline-warning">Edit</a>
              <a href="{{ path('association_delete', {"id": association.id}) }}" class="btn btn-outline-danger" onclick="return confirm('Cette action est définitive, êtes vous sûr de vouloir supprimer cette association du site?');">Delete</a>
            </div>
          </div>
        {% endfor %}
      </div>
      {% endif %}
      <div class="d-flex flex-row justify-content-between">
        {% for association in user.associations %}
          <div class="media bg-dark p-3 m-3">
            <a class="d-flex" href="#">
              <img src="{{ asset( 'img/logo/' ~ association.assLogo ) }}"  class="ass_logo" alt="">
            </a>
            <div class="media-body">
              <h5>{{association.assNom}}</h5>
              {{association.assDescription}}
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

    <a href="{{ path('user_edit', {'id': user.id}) }}">Edit</a>
{% endblock %}