ecoView/src/Entity/Association.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\AssociationRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass=AssociationRepository::class)
 */
class Association
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ass_nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ass_code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ass_description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ass_adresse;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $ass_cp;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ass_ville;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="associations")
     */
    private $ass_membres;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ass_site;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $ass_created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $ass_added_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ass_logo;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="associationsGerees")
     */
    private $ass_president;

    public function __construct()
    {
        $this->ass_members = new ArrayCollection();
        $this->ass_added_at = new DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAssNom(): ?string
    {
        return $this->ass_nom;
    }

    public function setAssNom(string $ass_nom): self
    {
        $this->ass_nom = $ass_nom;

        return $this;
    }

    public function getAssCode(): ?string
    {
        return $this->ass_code;
    }

    public function setAssCode(string $ass_code): self
    {
        $this->ass_code = $ass_code;

        return $this;
    }

    public function getAssDescription(): ?string
    {
        return $this->ass_description;
    }

    public function setAssDescription(string $ass_description): self
    {
        $this->ass_description = $ass_description;

        return $this;
    }

    public function getAssAdresse(): ?string
    {
        return $this->ass_adresse;
    }

    public function setAssAdresse(?string $ass_adresse): self
    {
        $this->ass_adresse = $ass_adresse;

        return $this;
    }

    public function getAssCp(): ?int
    {
        return $this->ass_cp;
    }

    public function setAssCp(?int $ass_cp): self
    {
        $this->ass_cp = $ass_cp;

        return $this;
    }

    public function getAssVille(): ?string
    {
        return $this->ass_ville;
    }

    public function setAssVille(string $ass_ville): self
    {
        $this->ass_ville = $ass_ville;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getAssMembres(): Collection
    {
        return $this->ass_membres;
    }

    public function addAssMember(User $assMembre): self
    {
        if (!$this->ass_membres->contains($assMembre)) {
            $this->ass_membres[] = $assMembre;
        }

        return $this;
    }

    public function removeAssMembre(User $assMembre): self
    {
        if ($this->ass_membres->contains($assMembre)) {
            $this->ass_membres->removeElement($assMembre);
        }

        return $this;
    }

    public function getAssSite(): ?string
    {
        return $this->ass_site;
    }

    public function setAssSite(?string $ass_site): self
    {
        $this->ass_site = $ass_site;

        return $this;
    }

    public function getAssCreatedAt(): ?\DateTimeInterface
    {
        return $this->ass_created_at;
    }

    public function setAssCreatedAt(?\DateTimeInterface $ass_created_at): self
    {
        $this->ass_created_at = $ass_created_at;

        return $this;
    }

    public function getAssAddedAt(): ?\DateTimeInterface
    {
        return $this->ass_added_at;
    }

    public function setAssAddedAt(\DateTimeInterface $ass_added_at): self
    {
        $this->ass_added_at = $ass_added_at;

        return $this;
    }

    public function getAssLogo(): ?string
    {
        return $this->ass_logo;
    }

    public function setAssLogo(?string $ass_logo): self
    {
        $this->ass_logo = $ass_logo;

        return $this;
    }

    public function getAssPresident(): ?User
    {
        return $this->ass_president;
    }

    public function setAssPresident(?User $ass_president): self
    {
        $this->ass_president = $ass_president;

        return $this;
    }
}

ecoView/src/Form/AssociationType.php
<?php

namespace App\Form;

use App\Entity\Association;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class AssociationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('ass_nom', TextType::class, [
                'label' => 'Name : '
            ])
            ->add('ass_code', TextType::class, [
                'label' => 'Code : '
            ])
            ->add('ass_site', TextType::class, [
                'label' => 'Web Site : '
            ])
            ->add('ass_adresse', TextType::class, [
                'label' => 'Adress : '
            ])
            ->add('ass_cp', TextType::class, [
                'label' => 'ZIP Code : '
            ])
            ->add('ass_ville', TextType::class, [
                'label' => 'City : '
            ])
            ->add('ass_description', TextType::class, [
                'label' => 'Description : '
            ])
            ->add('ass_president', TextType::class, [
                'label' => 'President : '
            ])
            ->add('ass_created_at',DateType::class, [
                'widget' => 'single_text',
            ])
            ->add('logo', FileType::class, [
                'mapped'=>false,
                'label'=>'Logo',
                'required'=>false,
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Merci d\'envoyer votre logo en jpg ou png',
                    ])
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Association::class,
        ]);
    }
}

ecoView/src/Controller/AssociationController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\Association;
use App\Form\AssociationType;
use App\Repository\AssociationRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/association")
 */
class AssociationController extends AbstractController
{
    /**
     * @Route("/", name="association_index", methods={"GET"})
     */
    public function index(AssociationRepository $associationRepository): Response
    {
        return $this->render('association/index.html.twig', [
            'associations' => $associationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="association_new", methods={"GET","POST"})
     */
    public function new(Request $request, SluggerInterface $slugger): Response
    {
        $association = new Association();
        $form = $this->createForm(AssociationType::class, $association);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            $logoFile = $form->get('logo')->getData();
            if ($logoFile) {
                $originalFilename = pathinfo($logoFile->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$logoFile->guessExtension();
                $association->setAssLogo($newFilename);

                try {
                    $logoFile->move(
                        $this->getParameter('logo_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    throw new Exception('erreur de déplacement du logo : '.$e->getMessage());
                }

            }

            $ass_president = $form->get('ass_president');
            if (!$ass_president){
                $association->setAssPresident($this->getUser());
            }

            $association->setAssAddedAt(new DateTime());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($association);
            $entityManager->flush();

            return $this->redirectToRoute('association_index');
        }

        return $this->render('association/new.html.twig', [
            'association' => $association,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="association_show", methods={"GET"})
     */
    public function show(Association $association): Response
    {
        return $this->render('association/show.html.twig', [
            'association' => $association,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="association_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Association $association, SluggerInterface $slugger): Response
    {
        $form = $this->createForm(AssociationType::class, $association);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // dd($form);
            $logoFile = $form->get('logo')->getData();
            if ($logoFile) {
                $originalFilename = pathinfo($logoFile->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$logoFile->guessExtension();
                $association->setAssLogo($newFilename);

                try {
                    $logoFile->move(
                        $this->getParameter('logo_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    throw new Exception('erreur de déplacement du logo : '.$e->getMessage());
                }

            }
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_show', ['id'=>$this->getUser()->getId()]);
        }

        return $this->render('association/edit.html.twig', [
            'association' => $association,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="association_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Association $association): Response
    {
        if ($this->isCsrfTokenValid('delete'.$association->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($association);
            $entityManager->flush();
        }

        return $this->redirectToRoute('association_index');
    }
}

ecoView/templates/association/_delete_form.html.twig
<form method="post" action="{{ path('association_delete', {'id': association.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ association.id) }}">
    <button class="btn">Delete</button>
</form>

ecoView/templates/association/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

ecoView/templates/association/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Association{% endblock %}

{% block body %}
    <h1>Edit Association</h1>
    <div class="container">
        {{ include('association/_form.html.twig', {'button_label': 'Update'}) }}

        <a href="{{ path('association_index') }}">back to list</a>

        {{ include('association/_delete_form.html.twig') }}
    </div>
{% endblock %}

ecoView/templates/association/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Association index{% endblock %}

{% block body %}
    <h1>Association index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Ass_name</th>
                <th>Ass_code</th>
                <th>Ass_site</th>
                <th>Ass_adresse</th>
                <th>Ass_cp</th>
                <th>Ass_ville</th>
                <th>Ass_description</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for association in associations %}
            <tr>
                <td>{{ association.id }}</td>
                <td>{{ association.assNom }}</td>
                <td>{{ association.assCode }}</td>
                <td>{{ association.assSite }}</td>
                <td>{{ association.assAdresse }}</td>
                <td>{{ association.assCp }}</td>
                <td>{{ association.assVille }}</td>
                <td>{{ association.assDescription }}</td>
                <td>
                    <a href="{{ path('association_show', {'id': association.id}) }}">show</a>
                    <a href="{{ path('association_edit', {'id': association.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('association_new') }}">Create new</a>
{% endblock %}

ecoView/templates/association/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Association{% endblock %}

{% block body %}
    <h1>Create new Association</h1>

    {{ include('association/_form.html.twig') }}

    <a href="{{ path('association_index') }}">back to list</a>
{% endblock %}

ecoView/templates/association/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Association{% endblock %}

{% block body %}
    <h1>Association</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ association.id }}</td>
            </tr>
            <tr>
                <th>Ass_name</th>
                <td>{{ association.assNom }}</td>
            </tr>
            <tr>
                <th>Ass_code</th>
                <td>{{ association.assCode }}</td>
            </tr>
            <tr>
                <th>Ass_site</th>
                <td>{{ association.assSite }}</td>
            </tr>
            <tr>
                <th>Ass_adresse</th>
                <td>{{ association.assAdresse }}</td>
            </tr>
            <tr>
                <th>Ass_cp</th>
                <td>{{ association.assCp }}</td>
            </tr>
            <tr>
                <th>Ass_ville</th>
                <td>{{ association.assVille }}</td>
            </tr>
            <tr>
                <th>Ass_description</th>
                <td>{{ association.assDescription }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('association_index') }}">back to list</a>

    <a href="{{ path('association_edit', {'id': association.id}) }}">edit</a>

    {{ include('association/_delete_form.html.twig') }}
{% endblock %}